### ISSUE TITLE
shortcode for md but not Rmd

### ISSUE THREAD

**Issue by ogansser** [J-Siu/blogdown-sk3-test#2]
The shortcode works for md post, but not for Rmd post.

**Comment by J-Siu** [comment]
How is rmd created? Is it just changing filename index.md to index.rmd?

PS: I don't know R at all and just learn a bit of RStudio yesterday.

**Comment by J-Siu** [comment]
Solution found.

Both delimiters are correct for hugo shortcode:

```
{{< youtube buiLez6AMU8 >}}
{{% youtube buiLez6AMU8 %}}
```

However, blogdown is only rendering the 2nd format`{{% ... %}}` in `.rmd`. (Both work in `.md`)

Maybe you can use this repo to open an issue report with blogdown.

**Comment by ogansser** [comment]
I do not know ehat is going on right now.

But all my Rmd generated files are not shown as the should.

I tried many things.

See:
http://gansser.de/post/2020-12-01-r-rmarkdown/

This ist from the original binario theme. I find not change anything.


Am Fr., 9. Apr. 2021 um 15:51 Uhr schrieb John Sing Dao Siu <
***@***.***>:

**Comment by ogansser** [comment]
There must be something wrong with the html rendering since yesterday.

Am Fr., 9. Apr. 2021 um 16:21 Uhr schrieb Oliver Gansser ***@***.***

**Comment by J-Siu** [comment]
Maybe you should reinstall blogdown, and make a new test project to just test a few simple pages to make sure blogdown is working correctly.

**Comment by ogansser** [comment]
Made this, but still don't work. I thing it has something to do with
blogdown. In an older Version it works (0.2)


Am Fr., 9. Apr. 2021 um 16:27 Uhr schrieb John Sing Dao Siu <
***@***.***>:

**Comment by J-Siu** [comment]
This is strange. My setup here is rstudio 4.0.5, blogdown 1.2, hugo 0.82.0.

After running `blogdown::build_site()`, I put public folder to a testing website and it is working.

Testing website: https://blogdown-sk3-test.jsiu.dev/

It seems theme is not applied to any rmd files at all.

**Comment by J-Siu** [comment]
See if https://github.com/J-Siu/hugo-theme-sk3/issues/28#issuecomment-816810141 helps.

**Comment by J-Siu** [comment]
Closing base on update of https://github.com/J-Siu/hugo-theme-sk3/issues/28#issuecomment-817960808
